// <auto-generated />
using System;
using FullTextSearch.DBCreator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FullTextSearch.DBCreator.Migrations
{
    [DbContext(typeof(AppsContext))]
    partial class AppsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FullTextSearch.Models.AppItem", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppAndroidRequirement");

                    b.Property<string>("AppCategory");

                    b.Property<string>("AppContentRating");

                    b.Property<string>("AppGenres");

                    b.Property<string>("AppInstalls");

                    b.Property<DateTime>("AppLastUpdate");

                    b.Property<string>("AppName");

                    b.Property<double?>("AppPrice");

                    b.Property<double?>("AppRating");

                    b.Property<int?>("AppReviews");

                    b.Property<double?>("AppSizeInKb");

                    b.Property<int>("AppType");

                    b.Property<string>("AppVersion");

                    b.HasKey("AppId");

                    b.ToTable("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
