FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["CodeCampDR.csproj", "."]
RUN dotnet restore "CodeCampDR.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "CodeCampDR.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "CodeCampDR.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "CodeCampDR.dll"]